#!/bin/bash

db_user=baikal
db_name=baikal
root_pwd=$(sudo cat /etc/yunohost/mysql)
mysql -u root -p$root_pwd -e "DROP DATABASE $db_name ; DROP USER $db_user@localhost ;"

# Removing executable files
sudo rm -rf /var/www/baikal
domain=$(sudo yunohost app setting baikal domain)
sudo rm -f /etc/nginx/conf.d/$domain.d/baikal.conf

# Restarting services
sudo service nginx reload
